# Generated by Django 5.0 on 2025-01-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
